apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      imagePullSecrets:
        - name: nexus-creds
      containers:
        - name: payments
          image: 192.168.1.140:5000/docker-images/payments:latest
          ports:
            - containerPort: 8080

